### ISSUE TITLE
Allow CSS to be registered as LESS for dependencies

### ISSUE THREAD

**Issue by seangates** [lasso-js/lasso-less#7]
Currently CSS and LESS are pulled in separately, making some complex dependency trees difficult to trace when both are used. I ran into this today where I needed CSS to be included as a dependency for the LESS in a deeply-nested component I was editing. Following down the chain of 7-8 optimizer.json (now browser.json) files to find the culprit was laborious as there were many combinations to traverse.

Therefore, if CSS could be included as a style sheet type for LESS files (optional via config, of course) it would allow flexibility when dealing with CSS output.

Code in question: https://github.com/lasso-js/lasso-less/blob/master/lib/index.js

```
var less = require('less');

module.exports = function(lasso, config) {
    config.less = config.less || less;
    lasso.dependencies.registerStyleSheetType('less', require('./dependency-less')(config, lasso));
    lasso.dependencies.registerPackageType('less-import', require('./dependency-less-import')(config, lasso));
};
```

**Comment by philidem** [comment]
@seangates I don't think it would be a good idea to make the `lasso-less` plugin handle raw CSS. Even though I prefer LESS over CSS and other CSS-preprocessors, I don't think we should make it the handler for raw CSS files. Support for CSS is built into Lasso.js because we didn't want developers to have to install a plugin to use that.

Any chance you can simply rename all of the CSS files to *.less?

FYI: `optimizer.json` will still be supported to ease migration but `browser.json` would be preferred going forward since the file is used to control browser bundling behavior.

**Comment by philidem** [comment]
Also, maybe we need to find a better way to debug dependency graph issues?

**Comment by patrick-steele-idem** [comment]
@philidem, @seangates and I talked about this offline. In his use case he has third-party components that are using raw CSS files and the ordering is getting messed up. The plan that we discussed was to allow the `optimizer-less` plugin to be optionally configured to also handle raw CSS files (opt-in only).

**Comment by seangates** [comment]
@philidem I completely agree that better tooling for seeing how the dependency graph is generated, either step by step or as output, would be very helpful. Was thinking on Friday about how I might go about working on something like that, but haven't gotten very far yet.
